global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-docker
  marketplace-ami: false
  reporting: true
  regions:
    - us-east-1
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  docker:
    template_file: quickstart-docker.template
    parameter_input: quickstart-docker.json
