global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-docker
  marketplace-ami: false
  reporting: true
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  docker:
    template_file: quickstart-docker.template
    parameter_input: quickstart-docker-us-east1.json 
	region:
	 - us-east-1
